export default[{ id: 1, 
brandname: "AudioWave", 
description: "Over-Ear Studio Headphones", 
rating: 4.4, 
originalPrice: 300,
 discount: 12, 
 image: "./../assets/studio_headphones.jpg", 
variants: ["Open Back", "Closed Back"], 
feedbacks: [ { text: "Crisp audio for music production!", rating: 5 }, { text: "A bit bulky for everyday use.", rating: 4 },
 ], 
 },
 
 {
  id: 2,
  brandname: "BassBoost",
  description: "Wireless Bass-Heavy Headphones",
  rating: 4.3,
  originalPrice: 180,
  discount: 15,
  image: "./../assets/bass_headphones.jpg", 
  variants: ["Standard", "XL Bass Edition"],
  feedbacks: [
    { text: "Powerful bass for immersive sound! Perfect for bass-heavy music genres like electronic dance music (EDM) or hip-hop.", rating: 5 },
    { text: "May not be ideal for all music genres. Listeners who prefer a more balanced soundscape may find the bass overpowering.", rating: 3.8 },
  ],
},
{
  id: 3,
  brandname: "ClearSound",
  description: "Noise-Cancelling Headphones",
  rating: 4.6,
  originalPrice: 220,
  discount: 8,
  image: "./../assets/noise_cancelling_headphones.jpg", 
  variants: ["Standard", "Pro with Ambient Mode"],
  feedbacks: [
    { text: "Excellent noise cancellation for focus! Blocks out ambient noise for a distraction-free listening experience, ideal for studying, working in noisy environments, or traveling.", rating: 5 },
    { text: "Battery life could be longer. For users who take long trips or use their headphones for extended periods, battery life may be a concern.", rating: 4.2 },
  ],
},
{
  id: 4,
  brandname: "SportZone",
  description: "Wireless Workout Headphones",
  rating: 4.7,
  originalPrice: 130,
  discount: 10,
  image: "./../assets/workout_headphones.jpg",
  variants: ["Standard", "Waterproof Pro"],
  feedbacks: [
    { text: "Secure fit for active use! Designed to stay in place during exercise, even with vigorous movement.", rating: 5 },
    { text: "Sound quality may not be audiophile-grade. Prioritizes functionality and secure fit over high-fidelity sound reproduction.", rating: 4.4 },
  ],
},

{
  id: 5,
  brandname: "Harmony",
  description: "On-Ear Headphones",
  rating: 4.1,
  originalPrice: 80,
  discount: 0,
  image: "./../assets/on_ear_headphones.jpg", 
  variants: ["Standard", "Leather Ear Pads"],
  feedbacks: [
    { text: "Lightweight and comfortable for long listening sessions. On-ear design rests comfortably without feeling bulky.", rating: 4.5 },
    { text: "Sound isolation may not be as strong as over-ear models. Less effective at blocking out ambient noise compared to over-ear headphones.", rating: 3.9 },
  ],
},
{
  id: 5,
  brandname: "Harmony",
  description: "On-Ear Headphones",
  rating: 4.1,
  originalPrice: 80,
  discount: 0,
  image: "./../assets/on_ear_headphones.jpg", 
  variants: ["Standard", "Leather Ear Pads"],
  feedbacks: [
    { text: "Lightweight and comfortable for long listening sessions. On-ear design rests comfortably without feeling bulky.", rating: 4.5 },
    { text: "Sound isolation may not be as strong as over-ear models. Less effective at blocking out ambient noise compared to over-ear headphones.", rating: 3.9 },
  ],
},
{
  id: 5,
  brandname: "Harmony",
  description: "On-Ear Headphones",
  rating: 4.1,
  originalPrice: 80,
  discount: 0,
  image: "./../assets/on_ear_headphones.jpg", 
  variants: ["Standard", "Leather Ear Pads"],
  feedbacks: [
    { text: "Lightweight and comfortable for long listening sessions. On-ear design rests comfortably without feeling bulky.", rating: 4.5 },
    { text: "Sound isolation may not be as strong as over-ear models. Less effective at blocking out ambient noise compared to over-ear headphones.", rating: 3.9 },
  ],
},
{
  id: 6,
  brandname: "TravelBuds",
  description: "Wireless Earbuds with Charging Case",
  rating: 4.2,
  originalPrice: 60,
  discount: 20,
  image: "./../assets/travel_earbuds.jpg", 
  variants: ["Standard", "Pro with longer battery life"],
  feedbacks: [
    { text: "Convenient for travel and everyday use! Compact and portable, ideal for storing in a bag or pocket.", rating: 4.7 },
    { text: "Soundstage may not be as wide as over-ear headphones. Soundstage refers to the perceived width and depth of the audio, which can be less pronounced in earbuds compared to larger headphones.", rating:3.9},],},

  {
  id: 7,
  brandname: "CrystalVoice",
  description: "Gaming Headset with Microphone",
  rating: 4.5,
  originalPrice: 150,
  discount: 18,
  image: "./../assets/gaming_headset.jpg", // Replace with a relevant image path
  variants: ["Standard", "Surround Sound Edition"],
  feedbacks: [
    { text: "Clear microphone for communication! Ideal for online gaming and voice chat applications.", rating: 4.8 },
    { text: "May not be as comfortable for extended wear sessions. Designed for functionality over long-term comfort, which some users may find fatiguing after extended use.", rating: 4.1 },
  ],
},
{
  id: 8,
  brandname: "QuietZone",
  description: "Sleep Headphones",
  rating: 4.8,
  originalPrice: 40,
  discount: 5,
  image: "./../assets/sleep_headphones.jpg", // Replace with a relevant image path
  variants: ["Standard", "Soft Fabric Version"],
  feedbacks: [
    { text: "Comfortable for sleeping! Soft and breathable materials designed for all-night wear.", rating: 5 },
    { text: "Sound quality may be limited. Primarily focuses on noise-blocking functionality for sleep rather than high-fidelity audio reproduction.", rating: 4.5 },
  ],
},
{
  id: 9,
  brandname: "KidzFun",
  description: "Wired Headphones for Kids",
  rating: 4.6,
  originalPrice: 30,
  discount: 10,
  image: "./../assets/kids_headphones.jpg", // Replace with a relevant image path
  variants: ["Standard", "Fun Colors Edition"],
  feedbacks: [
    { text: "Durable and volume-limited! Designed to withstand drops and bumps, with built-in volume limiters to protect children's hearing.", rating: 5 },
    { text: "Sound quality may be basic. Prioritizes durability and safety over high-fidelity sound.", rating: 4.2 },
  ],
},
{
  id: 10,
  brandname: "HearAll",
  description: "Bone Conduction Headphones",
  rating: 4.2,
  originalPrice: 200,
  discount: 12,
  image: "./../assets/bone_conduction_headphones.jpg", // Replace with a relevant image path
  variants: ["Standard", "Waterproof Version"],
  feedbacks: [
    { text: "Open-ear design for situational awareness! Allows users to stay aware of their surroundings while listening to music or podcasts.", rating: 4.7 },
    { text: "Sound quality may not be as bass-heavy as traditional headphones. Bone conduction transmits sound through vibrations on the skull, which may result in a different listening experience compared to traditional headphones.", rating: 3.9 },
  ],
},


 ]