export default [
  {
    id: 1,
    brandname: 'SoundMax',
    description: 'Wireless Noise Cancelling',
    rating: 4.2,
    originalPrice: 250,
    discount: 20,
    image: 'Registration.jpg',
  },
  {
    id: 2,
    brandname: 'AudioPro',
    description: 'Studio Quality Sound',
    rating: 4.5,
    originalPrice: 180,
    discount: 15,
    image: 'Registration.jpg',
  },
  {
    id: 3,
    brandname: 'BeatBass',
    description: 'Deep Bass Experience',
    rating: 4.1,
    originalPrice: 220,
    discount: 25,
    image:'profile.png',
  },
  {
    id: 4,
    brandname: 'SoundWave',
    description: 'Crystal Clear Audio',
    rating: 4.4,
    originalPrice: 200,
    discount: 10,
    image: 'Regisration.jpg',
  },
  {
    id: 5,
    brandname: 'Auriculr',
    description: 'Comfortable Fit Design',
    rating: 4.3,
    originalPrice: 280,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 6,
    brandname: 'HeadRush',
    description: 'Adrenaline Pumping Sound',
    rating: 4.6,
    originalPrice: 300,
    discount: 15,
    image: 'profile.png',
  },
  {
    id: 7,
    brandname: 'AudioFlyte',
    description: 'Lightweight Portable Design',
    rating: 4.2,
    originalPrice: 230,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 8,
    brandname: 'SoundScape',
    description: 'Immersive Audio Experience',
    rating: 4.5,
    originalPrice: 250,
    discount: 10,
    image: 'profile.png',
  },
  {
    id: 9,
    brandname: 'BeatBazaar',
    description: 'Budget Friendly Option',
    rating: 4.1,
    originalPrice: 180,
    discount: 15,
    image:'profile.png',
  },
  {
    id: 10,
    brandname: 'AudioRise',
    description: 'Elevate Your Music',
    rating: 4.3,
    originalPrice: 220,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 11,
    brandname: 'SoundSurge',
    description: 'Powerful Bass Response',
    rating: 4.4,
    originalPrice: 280,
    discount: 10,
    image: 'profile.png',
  },
  {
    id: 12,
    brandname: 'HeadSpace',
    description: 'Comfortable Noise Cancelling',
    rating: 4.6,
    originalPrice: 300,
    discount: 15,
    image: 'profile.png',
  },
  {
    id: 13,
    brandname: 'AudioPulse',
    description: 'Rhythmic Bass Boost',
    rating: 4.2,
    originalPrice: 230,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 14,
    brandname: 'SoundZone',
    description: 'Total Immersion Sound',
    rating: 4.5,
    originalPrice: 250,
    discount: 10,
    image: 'profile.png',
  },
  {
    id: 15,
    brandname: 'BeatFusion',
    description: 'Seamless Sound Integration',
    rating: 4.1,
    originalPrice: 200,
    discount: 15,
    image: 'profile.png',
  },
  {
    id: 16,
    brandname: 'AudioVibe',
    description: 'Vibrant Sound Experience',
    rating: 4.3,
    originalPrice: 220,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 17,
    brandname: 'SoundRush',
    description: 'Adrenaline Pumping Bass',
    rating: 4.4,
    originalPrice: 280,
    discount: 10,
    image: 'profile.png',
  },
  {
    id: 18,
    brandname: 'HeadWave',
    description: 'Crystal Clear Audio',
    rating: 4.6,
    originalPrice: 300,
    discount: 15,
    image: 'profile.png',
  },
  {
    id: 19,
    brandname: 'AudioBite',
    description: 'Snappy Fresh Sound',
    rating: 4.2,
    originalPrice: 230,
    discount: 20,
    image: 'profile.png',
  },
  {
    id: 20,
    brandname: 'SoundStorm',
    description: 'Thunderous Bass Experience',
    rating: 4.5,
    originalPrice: 250,
    discount: 10,
    image: 'profile.png',
  },
];